#' Example Corpus: Italian Parliamentary Speeches (2018–2022)
#'
#' A tokenized `quanteda` tokens object from Italian parties.
#'
#' @docType data
#' @usage data(corpus_ITA)
#' @format A \code{quanteda::tokens} object with document-level variables
#'   including \code{Speaker_party} and \code{year_month}.
#' @source https://clarin.si/repository/xmlui/handle/11356/1864
#' @keywords datasets
"corpus_ITA"

#' Demo Cosine Similarity Results (Italy)
#'
#' Example cosine similarity results generated by \code{calc_cosSim()}
#' for Italian political party word embeddings (FdI, 2018),
#' focusing on immigration-related terms.
#'
#' @docType data
#' @usage data(demo_cossim_IT)
#'
#' @format A list of length 1. The list contains a data frame with the
#'
#' @source Generated using \code{calc_cosSim()} with Italian parliamentary text data
#' @keywords datasets
"demo_cossim_IT"

#' Dictionary List for Illiberalism Measurement
#'
#' A list of country- or language-specific dictionaries used to compute
#' liberal and illiberal word embeddings. Each element of the list is a
#' data frame containing a column \code{term} and paired columns of the
#' form \code{<term>_liberal} and \code{<term>_illiberal}.
#'
#' @docType data
#' @usage data(dictionaries)
#' @format A named list of length 13. Each element is a data frame with:
#' \describe{
#'   \item{country}{Country or scope identifier (e.g. \code{"all"})}
#'   \item{term}{Dictionary concept (e.g. immigration, sovereignty)}
#'   \item{<term>_liberal}{Character vector of liberal seed words}
#'   \item{<term>_illiberal}{Character vector of illiberal seed words}
#' }
#'
#' @keywords datasets
"dictionaries"

